### ISSUE TITLE
A small typo in stylegan2_generator

### ISSUE THREAD

**Issue by Usman-Rafique** [genforce/genforce#1]
Thanks for releasing this awesome library. A small typo:

`if np.ranodm.uniform() < style_mixing_prob:` -> `if np.random.uniform() < style_mixing_prob:`

https://github.com/genforce/genforce/blob/ae6f9cf55f080e9c365b9a7d259b92fda5f50447/models/stylegan2_generator.py#L187

**Comment by ShenYujun** [comment]
Thanks for pointing this out!
