### ISSUE TITLE
Force train code to run on 1 GPU

### ISSUE THREAD

**Issue by steffeol** [genforce/genforce#12]
Helloo

I'm working on a server, but I don't have sudoers rights. It seems to naively run the train code, according to the instructions one has to run it on multiple GPUs e.g. have sudo rights. Is there a way to use train with only 1 GPU to circumvent needing sudo rights. During stepping through the code, we found that the error occurs when using dist.init_process_group in utils/misc.py line 27.

Without changing to much in the pipeline, is the a way to fix this. 

Best regards

**Comment by steffeol** [comment]
The error code is 
-bash: ./scripts/dist_train.sh: Permission denied
We tried to set the GPU environment variable to 1 in order to use only 1 GPU (The server would theoretically have 10)

**Comment by justimyhxu** [comment]
You can use `chmod +x scripts/dist_train.sh` to modify the permission for the file.

**Comment by steffeol** [comment]
Thanks for the help, it worked!
