### ISSUE TITLE
Slow in debugging using pdb

### ISSUE THREAD

**Issue by fungtion** [genforce/genforce#14]
When I using pdb to debug `dist_train.sh`, it becomes very slow after stopped at the breakpoint, and I can not print any debug information like `p xxx`. Can you help me?

**Comment by justimyhxu** [comment]
What does mean `using pdb to debug dist_train.sh,`? Can you give more information about your debug process?

**Comment by fungtion** [comment]
That means insert breakpoint by adding "pdb.set_trace()" to some scipt, and then run `dist_train.sh`, and the process will stop at the breakpoint. But I found when I want to print some variables using the command "p [variable]", I can hardly type this command.

**Comment by fungtion** [comment]
I found a similar question [here](https://discuss.pytorch.org/t/interactive-debug-in-distributed-launch/41385), it is the problem of the distributed.launch. Thanks.
