### ISSUE TITLE
Convert2genforce stylegan2 get collapse image

### ISSUE THREAD

**Issue by huaji0353** [genforce/genforce#15]
all size well done

but these gen image all collapse
![image](https://user-images.githubusercontent.com/26929386/102889396-8bba7280-4495-11eb-9349-72d22d44c945.png)

stylegan2 Convert2genforce Hard coded
[My Convert code](https://gist.github.com/huaji0353/25e1631112819121f6525bad2930a19e)
[My gen code](https://gist.github.com/huaji0353/324af73f28ea3cb53c96aa37a4307874)
model is **2020-01-11-skylion-stylegan2-animeportraits-networksnapshot-024664**

Model Origin pytorch code:
[1](https://github.com/Tetratrio/stylegan2_pytorch)
[2](https://github.com/rosinality/stylegan2-pytorch)

if genforce default has any different parameter configuration?

**Comment by limbo0000** [comment]
Hi @huaji0353, sorry about that I am not very familiar with other implementations \ie their parameter configurations. The only reference for us is the official one ([v1](https://github.com/NVlabs/stylegan), [v2](https://github.com/NVlabs/stylegan2)). In your case, I didn't find any converting test to check whether the output of each layer is the same. I guess introducing such testing could help you find the differences across various repos.

**Comment by huaji0353** [comment]
Thank you very much for your guidance!
I solved using [convert_tf_weights](https://github.com/genforce/higan/blob/master/models/stylegan2_generator.py#L49)
[related issue](https://github.com/genforce/sefa/issues/3)

[My Convert code](https://gist.github.com/huaji0353/5d8cd7678e431ef00e2eb2ed2b50ea30)
