### ISSUE TITLE
Could you provide the image list used to train stylegan_celeba_partial256?

### ISSUE THREAD

**Issue by njuaplusplus** [genforce/genforce#17]
Thank you for this project.
I saw there is a pre-trained weight 'stylegan_celeba_partial256' for StyleGAN. I wonder what images are used to train?

**Comment by ShenYujun** [comment]
CelebA dataset is used. But the faces are not fully aligned like FF-HQ or CelebA-HQ.

**Comment by njuaplusplus** [comment]
Thank you for your reply. 
But according to your [MODEL_ZOO.md](https://github.com/genforce/genforce/blob/master/MODEL_ZOO.md), 103,706 samples were used to train the stylegan_celeba_partial256. But CelebA dataset contains 202,599 samples.

I would like to know the list of the 103,706 samples. And what're the criteria to select the 103,706 samples? Filtering the low-resolution images?

**Comment by ShenYujun** [comment]
Please refer to this [code](https://github.com/NVlabs/ffhq-dataset/blob/bb67086731d3bd70bc58ebee243880403726197a/download_ffhq.py#L259) for face alignment. For partially aligned case, please comment out Line 339-341 and replace with
```
crop = (int(np.floor(min(quad[:, 0]))), int(np.floor(min(quad[:, 1]))),
        int(np.ceil(max(quad[:, 0]))), int(np.ceil(max(quad[:, 1]))))
img = img.crop(crop)
if min(img.size) >= 256:
    img = img.resize((output_size, output_size), Image.ANTIALIAS)
    img.save(save_path)
```
You are right that we use `min(img.size) >= 256` to filter low-resolution images.

**Comment by njuaplusplus** [comment]
I see. Thank you so much!

**Comment by njuaplusplus** [comment]
Hi @ShenYujun, I found the replacement in the code needs the `quad` variable, which was computed from `json_data` in the original ffhq code. I wonder where I can get the `json_data` for celeba. It would be great if you can share the code and data.

Thank you very much!

**Comment by ShenYujun** [comment]
The `quad` variable is computed based on facial landmarks. Please check this [code](https://github.com/NVlabs/ffhq-dataset/blob/bb67086731d3bd70bc58ebee243880403726197a/download_ffhq.py#L297) as the reference. There are many ways for landmark detection. For example, you can try `dlib`. Also, if I remember correctly, the official CelebA dataset has already provided the five keypoints.

**Comment by njuaplusplus** [comment]
Yes. I found the CelebA annotations provide those points. Though the FFHQ's code can not be applied directly, I think I can figure it out. Thank you very much.
