### ISSUE TITLE
Will you provide the pretrained model of PGGAN on the FFHQ or CelebA-HQ dataset?

### ISSUE THREAD

**Issue by gsygsygsy123** [genforce/genforce#20]
Dear Authors,
I so appreciate your contribution which is helpful to the whole community.  I wonder whether you can release the PGGAN model pretrained on FFHQ or CelebA-HQ? Thanks so much.

**Comment by ShenYujun** [comment]
It has already been included in the [Model Zoo](https://github.com/genforce/genforce/blob/master/MODEL_ZOO.md). [Here](https://mycuhk-my.sharepoint.com/:u:/g/personal/1155082926_link_cuhk_edu_hk/EW_3jQ6E7xlKvCSHYrbmkQQBAB8tgIv5W5evdT6-GuXiWw?e=gRifVa&download=1) is a quick reference for you, which is the model pre-trained on CelebA-HQ.

**Comment by gsygsygsy123** [comment]
Opzz... Thanks for your correction. BTW, how do you rescale FFHQ from 1024x1024 to 256x256? Bicubic downsample?

**Comment by ShenYujun** [comment]
I would recommend to resize the image with a maximum scale 2. For example, to downsample a 1024x1024 image to 256x256, please use the 512x512 resolution as an intermediate step.

**Comment by gsygsygsy123** [comment]
Thanks! You're so nice! 😊

**Comment by gsygsygsy123** [comment]
Thanks! You're so nice! 😊
