### ISSUE TITLE
How we can train our own dataset using stylegan model, what should be the settings?

### ISSUE THREAD

**Issue by mer93** [genforce/genforce#23]

**Comment by ShenYujun** [comment]
You can definitely train on your own data. For this purpose, please prepare the data (we recommend using `zip` format) as well as a configuration file, like [this](https://github.com/genforce/genforce/blob/master/configs/stylegan_ffhq256.py). You can customize your own hyper-parameters based on the dataset (such as image resolution, number of training samples, etc.).

**Comment by mer93** [comment]
Thanks It worked

**Comment by mer93** [comment]
I have 2 questions:
1) My data is in the form of grayscale images. So is it possible to train stylegan and pggan from genforce pytorch library. As i have tried style gan it does not work on grayscale images.
2) closed form Semantic Factorisation algorithm can be applied to the grayscale images?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ShenYujun** [comment]
Yes to both of these questions.

**Comment by mer93** [comment]
But the stylegan code has default settings of image channel 3. Could you please elaborate me how i can apply stylegan to my dataset. I need some guidance.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ShenYujun** [comment]
Add a setting in your configuration file. Add `image_channels=1` in `modules/generator/model` and `modules/discriminator/model`. Please refer to this [line](https://github.com/genforce/genforce/blob/30387208f662284f2fa30b646955d94cd9e8fb49/configs/stylegan_ffhq256.py#L41). You may also need to change this [line](https://github.com/genforce/genforce/blob/30387208f662284f2fa30b646955d94cd9e8fb49/metrics/fid.py#L30) to check the image shape. If `images.shape[1] == 1`, repeat it for 3 times since inception model only accepts 3-channel image.

**Comment by mer93** [comment]
Could you elaborate more the changes made in inception model. As it is giving error in my case.

**Comment by ShenYujun** [comment]
Something like
```
if images.shape[1] == 1:
    images = torch.tile(images, (1, 3, 1, 1))
```

**Comment by mer93** [comment]
After making changes in the metrics/fid.py file, It gives following error
**ValueError: The input tensor should be with shape [batch_size, channel, height, width], where `channel` equals to 1, `height`, `width` equal to 64!
But `torch.Size([32, 3, 64, 64])` is received!**

**Comment by ShenYujun** [comment]
How about setting `colorful_images = torch.tile(images, (1, 3, 1, 1)) `

**Comment by mer93** [comment]
![Screenshot (153)](https://user-images.githubusercontent.com/40052501/117526274-73439280-b007-11eb-91c3-1bee0d792ebe.png)

**Comment by ShenYujun** [comment]
Change Line 33 to `colourful_images`?

**Comment by mer93** [comment]
features = inception_model(colorful_images, output_logits=False)
like this?

**Comment by mer93** [comment]
> Change Line 33 to `colourful_images`?

It did not work for my gray scale dataset. Could you elaborate more.
