### ISSUE TITLE
Randomize noise

### ISSUE THREAD

**Issue by mehdizemni** [genforce/genforce#27]
Hello
Thank your for this implementation and all the interesting papers you have published!!
In your styleganv1 implementation you are using constant noise for layers {1 to last layer} except for layer0. 
In layer0, the noise is random and therefore the corresponding NoiseApplyingLayer is trained with different noise vectors but all other layers are trained with the same noise vector (constant vector for each layer). 
I wanted to know why do you randomize only the first noise vector. Your pretrained models were trained like this?
Thank you !
![cap](https://user-images.githubusercontent.com/72700677/128861502-ccc64a65-14d9-4d8c-abbf-7e93befd26fb.PNG)

**Comment by ShenYujun** [comment]
Good point! This should be a bug and thanks for pointing it out! We will fix it as soon as possible.
