### ISSUE TITLE
Training StyleGAN on Cityscapes

### ISSUE THREAD

**Issue by weihaox** [genforce/genforce#9]
Hi, thanks for your awesome work. 
I noticed you mentioned Cityscapes Dataset in the Model Zoo. I wonder how to train the 1024 * 512 size image for StyleGAN, directly resize or crop to 512 * 512? 
Thanks!

**Comment by ShenYujun** [comment]
Typically, you can centrally crop the image on the 1024 side. Or, if you like, you can randomly crop 512 pixels from the 1024 side.

**Comment by weihaox** [comment]
Thank you!
